import os
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), '.env'))

DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "port": int(os.getenv("DB_PORT", 5432)),
    "database": os.getenv("DB_NAME", "samplehunt"),
    "user": os.getenv("DB_USER", "postgres"),
    "password": os.getenv("DB_PASSWORD", "berke")
}

SCRAPERAPI_KEY = os.getenv("SCRAPERAPI_KEY", "")
MAX_VIEW_COUNT = int(os.getenv("MAX_VIEW_COUNT", 100000))

SEARCH_KEYWORDS = [
    "1970s rare soul vinyl",
    "1960s rare soul obscure",
    "1970s rare funk groove",
    "1980s rare funk soul",
    "rare northern soul 45",
    "1970s gospel soul obscure",
    "rare soul ballad 1960s",
    "obscure motown deep cut",
    "1960s rare modal jazz",
    "1970s jazz fusion obscure",
    "1970s free jazz rare",
    "1960s hard bop rare vinyl",
    "1970s post bop obscure",
    "1950s cool jazz rare",
    "1970s latin jazz rare",
    "1960s soul jazz obscure",
    "1990s underground hip hop rare",
    "1980s rap obscure vinyl",
    "1990s boom bap rare",
    "east coast hip hop 1990s obscure",
    "west coast rap 1990s rare",
    "1990s jazzy hip hop instrumental",
    "golden era hip hop rare",
    "1990s lo fi hip hop obscure",
    "1980s rare synth pop obscure",
    "1970s kosmische elektronik rare",
    "1980s italo disco obscure",
    "1990s rare house music",
    "1990s rare techno detroit",
    "1990s ambient electronic obscure",
    "1980s new wave electronic rare",
    "1970s electronic experimental obscure",
    "1970s psychedelic rock rare",
    "1960s garage rock obscure",
    "1970s progressive rock rare",
    "1970s krautrock obscure",
    "1970s hard rock rare",
    "1970s punk rock obscure",
    "1980s post punk rare",
    "1960s psych pop rare",
    "1970s roots reggae rare",
    "1970s dub reggae obscure",
    "1970s ska rocksteady rare",
    "1960s jamaican ska obscure",
    "1970s dub plate rare",
    "1980s dancehall early obscure",
    "1970s reggae vinyl rare",
    "1970s conscious reggae obscure",
    "1970s cumbia obscure",
    "1970s salsa rare",
    "1970s latin boogaloo rare",
    "1970s bossa nova rare",
    "1970s latin rock obscure",
    "1960s cha cha rare",
    "1970s samba rare vinyl",
    "1970s latin soul obscure",
    "1970s afrobeat rare",
    "1970s highlife ghana obscure",
    "1970s ethiopian music rare",
    "1970s african funk rare",
    "1970s afro soul obscure",
    "1970s turkish psychedelic rare",
    "1970s world music obscure",
    "1970s arabesk rare",
    "1970s library music rare",
    "1970s film score obscure",
    "1970s soundtrack rare",
    "1960s library music obscure",
    "1970s classical orchestral rare",
    "1970s italian library music",
    "1970s cinematic music rare",
    "1960s film score obscure",
    "1970s folk rare vinyl",
    "1970s blues guitar obscure",
    "1960s delta blues rare",
    "1970s country instrumental rare",
    "1970s bluegrass obscure",
    "1960s folk revival rare",
    "1970s acoustic blues rare",
    "1960s country soul obscure",
]

EXCLUDE_KEYWORDS = [
    "sample pack", "drum kit", "drumkit", "loops", "stems",
    "multitrack", "acapella", "one shot", "hit hat", "hihat",
    "how to make", "how to", "tutorial", "type beat", "typebeat",
    "fl studio", "ableton", "logic pro", "maschine", "mk808",
    "free download", "mp3 download", "wav download",
    "remix", "mashup", "cover",
    "type beat", "typebeat", "free type beat", "rap beat",
    "trap beat", "drill beat", "boom bap beat", "lofi beat",
    "free beat", "instrumental beat", "beat making", "beat tutorial",
    "vibe", "vibes", "vibing", "chill vibe", "good vibes", "bad vibes",
    "vibe check", "vibes only", "vibe patrol", "pure vibes", "vibe mode",
    "podcast", "podcast episode", "episod", "bölüm", "guest", "interview",
    "ai generated", "ai music", "ai song", "ai cover", "ai version",
    "artificial intelligence", "chatgpt", "suno", "udio", "loudme",
    "michael jackson", "beyonce", "drake", "kanye west", "jay z", "jay-z",
    "eminem", "taylor swift", "rihanna", "kendrick lamar", "frank ocean",
    "the weeknd", "travis scott", "21 savage", "post malone",
    "dr dre", "snoop dogg", "ice cube", "nas", "biggie", "2pac", "tupac",
    "madonna", "prince", "david bowie", "led zeppelin", "the beatles",
    "rolling stones", "pink floyd", "bob dylan", "bruce springsteen",
    "stevie wonder", "marvin gaye", "james brown", "otis redding",
    "aretha franklin", "ray charles", "sam cooke",
    "miles davis", "john coltrane", "thelonious monk", "charlie parker",
    "bob marley", "peter tosh",
    "stolen", "rip off", "plagiarism", "fake", "not music",
    "reaction", "ranking", "top 10", "best of", "greatest hits",
    "full discography", "complete collection",
    "lyrics only", "lyric video", "audio only", "music video",
]

SEARCH_DELAY = int(os.getenv("SEARCH_DELAY", 2))
MAX_RESULTS_PER_KEYWORD = int(os.getenv("MAX_RESULTS_PER_KEYWORD", 10))
