import re

STYLE_KEYWORDS = {
    "Abstract": ["abstract", "avant-garde", "experimental"],
    "Acid": ["acid", "acid house", "acid jazz"],
    "Acoustic": ["acoustic", "unplugged"],
    "Afrobeat": ["afrobeat", "afro"],
    "Alternative": ["alternative", "alt rock"],
    "Ambient": ["ambient", "atmospheric", "soundscape", "soundscapes"],
    "Avant-garde": ["avant-garde", "avantgarde", "experimental"],
    "Ballad": ["ballad", "balad"],
    "Baroque": ["baroque"],
    "Bass": ["bass", "bass music", "bassline"],
    "Bebop": ["bebop", "bop"],
    "Big Band": ["big band", "swing"],
    "Blues": ["blues", "blues rock", "chicago blues", "delta blues", "electric blues"],
    "Bolero": ["bolero"],
    "Bossa Nova": ["bossa nova", "bossa"],
    "Breakbeat": ["breakbeat", "breaks"],
    "Brit Pop": ["brit pop", "britpop"],
    "Calypso": ["calypso"],
    "Chanson": ["chanson", "french pop"],
    "Chicago Blues": ["chicago blues"],
    "Chillout": ["chillout", "chill"],
    "Choral": ["choral", "choir"],
    "City Pop": ["city pop", "citypop", "japanese city pop"],
    "Classic Rock": ["classic rock", "oldies rock"],
    "Classical": ["classical", "orchestral", "orchestra"],
    "Contemporary Jazz": ["contemporary jazz", "modern jazz"],
    "Country": ["country", "americana", "country rock"],
    "Dance": ["dance", "dance-pop", "eurodance"],
    "Dark Ambient": ["dark ambient", "dark"],
    "Deep House": ["deep house", "deep"],
    "Disco": ["disco", "disco funk"],
    "Doo Wop": ["doo wop", "doowop"],
    "Downtempo": ["downtempo", "chillout", "lounge"],
    "Dub": ["dub", "dubstep", "dubwise"],
    "Easy Listening": ["easy listening", "background"],
    "Electro": ["electro", "electronic", "electronic music"],
    "Emo": ["emo", "emotional"],
    "Ethereal": ["ethereal", "dreamy", "dream pop"],
    "Euro-Disco": ["euro disco", "euro-disco"],
    "Euro-House": ["euro house", "eurohouse"],
    "Flamenco": ["flamenco", "spanish guitar"],
    "Folk": ["folk", "folk rock", "indie folk"],
    "Funk": ["funk", "p-funk", "psychedelic funk", "funky"],
    "Fusion": ["fusion", "jazz fusion", " jazz-rock"],
    "Garage": ["garage", "garage rock"],
    "Gospel": ["gospel", "gospel soul", "church"],
    "Gothic": ["gothic", "goth rock", "gothic rock"],
    "Hard Bop": ["hard bop", "hardbop"],
    "Hard Rock": ["hard rock", "hardrock"],
    "Heavy Metal": ["heavy metal", "metal", "heavy"],
    "Hi-NRG": ["hi-nrg", "hinrg"],
    "Hindustani": ["hindustani", "indian classical"],
    "House": ["house", "deep house", "tech house"],
    "IDM": ["idm", "intelligent dance"],
    "Indie": ["indie", "indie rock", "indie pop"],
    "Industrial": ["industrial", "industrial rock"],
    "Instrumental": ["instrumental", "instruments only"],
    "Italo-Disco": ["italo disco", "italo-disco", "italo"],
    "Jazz": ["jazz", "jazz funk", "modal", "smooth jazz"],
    "Jazz-Funk": ["jazz-funk", "jazz funk"],
    "Jazz-Rock": ["jazz-rock", "jazz rock"],
    "J-Pop": ["j-pop", "jpop", "japanese pop"],
    "Latin": ["latin", "salsa", "merengue", "samba"],
    "Latin Jazz": ["latin jazz", "afro-cuban jazz"],
    "Lo-Fi": ["lo-fi", "lofi", "lo firap"],
    "Lounge": ["lounge", "exotica", "loung"],
    "Marches": ["march", "marches"],
    "Medieval": ["medieval", "renaissance"],
    "Minimal": ["minimal", "minimalist", "minimal techno"],
    "Mod": ["mod", "ska", "two tone"],
    "Modal": ["modal", "modal jazz"],
    "Motown": ["motown", "motown soul"],
    "Neo-Soul": ["neo soul", "neosoul", "neo-soul"],
    "New Age": ["new age", "newage", "spiritual"],
    "New Wave": ["new wave", "newwave", "synth pop"],
    "Noise": ["noise", "noise rock", "static"],
    "Nu Soul": ["nu soul", "nusoul", "alternative r&b"],
    "Opera": ["opera", "operatic"],
    "Orchestral": ["orchestral", "orchestra", "symphony"],
    "P-Funk": ["p-funk", "pfunk", "parliament funk"],
    "Pop": ["pop", "pop rock", "synth pop"],
    "Post-Punk": ["post-punk", "postpunk", "post punk"],
    "Post-Rock": ["post-rock", "postrock", "post rock"],
    "Power Pop": ["power pop", "powerpop"],
    "Prog Rock": ["prog rock", "progressive rock", "prog"],
    "Psychedelic": ["psychedelic", "psychedelia", "acid rock"],
    "Punk": ["punk", "punk rock"],
    "R&B": ["r&b", "rhythm and blues", "contemporary r&b"],
    "Ragga": ["ragga", "ragga jungle"],
    "Ragtime": ["ragtime", "rag time"],
    "Rap": ["rap", "hip hop", "hip-hop"],
    "Reggae": ["reggae", "rocksteady", "roots reggae"],
    "Renaissance": ["renaissance", "early music"],
    "Rhythm & Blues": ["rhythm and blues", "r&b", "blues"],
    "Rock": ["rock", "rock n roll", "rock & roll"],
    "Rocksteady": ["rocksteady", "ska"],
    "Romantic": ["romantic", "romantic era"],
    "Roots": ["roots", "roots reggae", "roots rad"],
    "Salsa": ["salsa", "salsa music"],
    "Samba": ["samba", "brazilian"],
    "Shoegaze": ["shoegaze", "shoegaze", "dream pop"],
    "Ska": ["ska", "ska rock"],
    "Soul": ["soul", "soul music", "southern soul", "smooth soul", "soul jazz"],
    "Soul-Jazz": ["soul-jazz", "soul jazz", "jazz"],
    "Soundtrack": ["soundtrack", "score", "film score", "movie"],
    "Space Age": ["space age", "space-age", "bachelor pad"],
    "Space Rock": ["space rock", "spacerock", "cosmic"],
    "Spoken Word": ["spoken word", "spokenword"],
    "Surf": ["surf", "surf rock", "instrumental rock"],
    "Swing": ["swing", "big band", "jazz swing"],
    "Synth-pop": ["synth-pop", "synthpop", "synth pop"],
    "Synthwave": ["synthwave", "retrowave", "outrun"],
    "Tango": ["tango", "argentine tango"],
    "Techno": ["techno", "techno music"],
    "Trance": ["trance", "trance music"],
    "Trip Hop": ["trip hop", "triphop", "trip-hop"],
    "Tropical": ["tropical", "tropical house", "caribbean"],
    "UK Garage": ["uk garage", "ukg", "garage house"],
    "Vaporwave": ["vaporwave", "vapor", "vapor synth"],
    "Vocal": ["vocal", "vocal jazz", "vocal music"],
    "World": ["world", "world music", "global"],
    "Zouk": ["zouk", "zouk music"]
}

class GenrePredictor:
    def predict(self, title, channel_name=""):
        text = f"{title} {channel_name}".lower()
        found_styles = []

        for style, keywords in STYLE_KEYWORDS.items():
            for keyword in keywords:
                if keyword in text:
                    found_styles.append(style)
                    break

        if not found_styles:
            return "unknown"

        return found_styles

    def extract_year(self, title):
        years = re.findall(r'\b(19[5-9]\d|20[0-2]\d)\b', title)
        if years:
            return int(years[0])
        return None